config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[index show new create destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  mount Sidekiq::Web => '/sidekiq'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'users#index'
end

app/models/application_record.rb
# Base class for all models
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/import_slot.rb
# Represents a slot in the import schedule
class ImportSlot < ApplicationRecord
  belongs_to :user

  def self.for_hour(hour)
    where(hour:).first
  end
end

app/models/language.rb
# Language model class
class Language < ApplicationRecord
  has_many :users, through: :languages_users
  has_many :languages_users, dependent: :destroy, class_name: 'LanguageUser'

  validates :name, presence: true, uniqueness: true

  def self.find_or_create_by_name(name)
    Language.find_or_create_by(name: name)
  end
end

app/models/language_user.rb
# model for the languages_users join table
#
class LanguageUser < ApplicationRecord
  belongs_to :language
  belongs_to :user
end

app/models/repository.rb
# Repository model class
class Repository < ApplicationRecord
  belongs_to :user
  belongs_to :language
end

app/models/user.rb
# User model class
class User < ApplicationRecord
  has_many :languages_users, dependent: :destroy, class_name: 'LanguageUser'
  has_many :languages, through: :languages_users
  has_many :repositories, dependent: :destroy
  has_many :import_slots, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  WEIGHTS = {
    star_count: 15,
    repository_count: 20,
    ruby_count: 30,
    python_count: 10,
    golang_count: -10,
    typescript_count: -15
  }.freeze

  LANG = {
    ruby: 'Ruby',
    python: 'Python',
    golang: 'Go',
    typescript: 'TypeScript'
  }.freeze

  def self.weighted_users(limit)
    User.includes(:languages_users, :languages, :repositories)
        .order(created_at: :desc)
        .limit(limit) # More than this will cause the scheduling constraints to fail
        .sort_by(&:weight)
  end

  def weight
    star_weight +
      repository_weight +
      ruby_weight +
      python_weight +
      golang_weight +
      typescript_weight
  end

  private

  def star_weight
    stars * User::WEIGHTS[:star_count]
  end

  def repository_weight
    repositories.count * User::WEIGHTS[:repository_count]
  end

  def ruby_weight
    languages.where(name: User::LANG['ruby']).count * User::WEIGHTS[:ruby_count]
  end

  def python_weight
    languages.where(name: User::LANG['python']).count * User::WEIGHTS[:python_count]
  end

  def golang_weight
    languages.where(name: User::LANG['golang']).count * User::WEIGHTS[:golang_count]
  end

  def typescript_weight
    languages.where(name: User::LANG['typescript']).count * User::WEIGHTS[:typescript_count]
  end
end

app/models/user_detail.rb
require 'scenic'

# Model for the user_details view
class UserDetail < ApplicationRecord
  belongs_to :userable, polymorphic: true

  def self.refresh
    Scenic.database.refresh_materialized_view(table_name, concurrently: false, cascade: false)
  end

  def readonly?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
# Controller for the User model.
class UsersController < ApplicationController
  before_action :set_user, only: %i[show destroy]

  # GET /users or /users.json
  def index
    @users = UserDetail.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    if create_user
      redirect_to user_url(@user), notice: 'User was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!
    UserDetail.refresh
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.includes(:languages, repositories: :language).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end

  def create_user
    @user = User.new(user_params)
    return false unless @user.save

    GithubImport.new.update_user(@user)
    UserDetail.refresh
    Schedule::Scheduler.new.update_imports
    true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Orri</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_short_user.html.erb
<div id="<%= dom_id user %>">
  <p><strong>Name: </strong><%= user.name %></p>
  <p><strong>Stars: </strong><%= user.stars %></p>
  <p><strong>Languages: </strong><%= user.languages.count %></p>
  <p><strong>Repositories: </strong><%= user.repositories.count %></p>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Stars:</strong>
    <%= user.stars %>
  </p>

  <p><strong>Languages:</strong></p>
  <% user.languages.each do |language| %>
    <p><%= language.name %></p>
  <% end %>

  <p><strong>Repositories:</strong></p>
  <% user.repositories.each do |repository| %>
    <p><%= repository.name %> :: Language: <%= repository.language.name %></p>
  <% end %>
</div>

app/views/users/_user_detail.html.erb
<div id="<%= dom_id user %>">
  <p><strong>Name: </strong><%= user.name %></p>
  <p><strong>Stars: </strong><%= user.stars %></p>
  <p><strong>Languages: </strong><%= user.language_count %></p>
  <p><strong>Repositories: </strong><%= user.repository_count %></p>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render "user_detail", user: %>
    <p><%= link_to "Show this user", user_path(user.id) %></p>
    <br/>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>